name: Release Charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  Release:
    name: Release Charts
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          since_last_remote_commit: true
          dir_names_max_depth: '2'
          dir_names: 'true'
          files: |
            charts/**

      - name: List all changed files markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            version=$(yq -r .version ${file}/Chart.yaml)
            helm package ${file} --version $version
            chart_name=$(echo $file | sed 's|charts/||')
            org=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
            helm push ${chart_name}-${version}.tgz oci://ghcr.io/${org}
          done
